{
 "title": "Cloud Resource Monitoring",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "CPU Utilization (AWS & AZURE)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "aws_ec2_cpu_utilization{instance_id=\"i-056250a7e38a6d0a7\"}",
     "legendFormat": "{{instance_id}} (AWS) CPU"
    }
   ]
  },
  {
   "title": "Disk I/O (Volume) AWS & AZURE",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "MBs" } },
   "targets": [
    {
     "expr": "aws_ebs_volumereadbytes{volume_id=\"vol-0e331fe5df83e4803\"}",
     "legendFormat": "{{volume_id}} (AWS) Read"
    },
    {
     "expr": "aws_ebs_volumewritebytes{volume_id=\"vol-0e331fe5df83e4803\"}",
     "legendFormat": "{{volume_id}} (AWS) Write"
    }
   ]
  },
  {
   "title": "Network In /Out (AWS & AZURE)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "KBs" } },
   "targets": [
    {
     "expr": "aws_ec2_networkin{instance_id=\"i-056250a7e38a6d0a7\"}",
     "legendFormat": "{{instance_id}} (AWS) In"
    },
    {
     "expr": "aws_ec2_networkout{instance_id=\"i-056250a7e38a6d0a7\"}",
     "legendFormat": "{{instance_id}} (AWS) Out"
    }
   ]
  }
 ]
}