{
 "title": "Cloud Resource Monitoring",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "CPU Utilization (AWS & AZURE)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "aws_ec2_cpu_utilization{cloud_provider=\"aws\"}",
     "legendFormat": "AWS - {{instance_id}}"
    },
    {
     "expr": "azure_vm_cpu_utilization{cloud_provider=\"azure\"}",
     "legendFormat": "Azure - {{vm_name}}"
    }
   ]
  },
  {
   "title": "Disk I/O (Volume) AWS & AZURE",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "MBs" } },
   "targets": [
    {
     "expr": "aws_ebs_volumereadbytes{cloud_provider=\"aws\"}",
     "legendFormat": "{{volume_id}} (AWS) Read "
    },
    {
     "expr": "aws_ebs_volumewritebytes{cloud_provider=\"aws\"}",
     "legendFormat": "{{volume_id}} (AWS) Write"
    },
    {
     "expr": "azure_vm_disk_read_bytes{cloud_provider=\"azure\"}",
     "legendFormat": "{{vm_name}} (Azure)  Read"
    },
    {
     "expr": "azure_vm_disk_write_bytes{cloud_provider=\"azure\"}",
     "legendFormat": "{{vm_name}} (Azure)  Write"
    }
   ]
  },
  {
   "title": "Network In /Out (AWS & AZURE)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "KBs" } },
   "targets": [
    {
     "expr": "aws_ec2_networkin{instance_id=\"i-056250a7e38a6d0a7\"}",
     "legendFormat": "{{instance_id}} (AWS) In"
    },
    {
     "expr": "aws_ec2_networkout{instance_id=\"i-056250a7e38a6d0a7\"}",
     "legendFormat": "{{instance_id}} (AWS) Out"
    },
    { "expr": "azure_vm_network_in", "legendFormat": "{{vm_name}} (Azure) In" },
    { "expr": "azure_vm_network_out", "legendFormat": "{{vm_name}} (Azure) Out" }
   ]
  }
 ]
}